### ISSUE TITLE
doesn't work with image "devopsqa/fortify"

### ISSUE THREAD

**Issue by ozbillwang** [LanikSJ/dfimage#146]
```
docker pull laniksj/dfimage
alias dfimage="docker run -v /var/run/docker.sock:/var/run/docker.sock --rm laniksj/dfimage"
docker pull devopsqa/fortify

dfimage devopsqa/fortify
Traceback (most recent call last):
  File "/root/entrypoint.py", line 56, in <module>
    __main__ = MainObj()
  File "/root/entrypoint.py", line 16, in __init__
    self._get_image(argv[-1])
  File "/root/entrypoint.py", line 32, in _get_image
    raise ImageNotFound("Image {} not found\n".format(img_hash))
__main__.ImageNotFound: Image devopsqa/fortify not found
```

I am looking for a image to run with fortify, and find it in hub.docker.com. I 'd like to reverse its Dockerfile. this image `devopsqa/fortify` is huge, 
```
docker images devopsqa/fortify
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
devopsqa/fortify    latest              9db34bb78a6e        2 years ago         3.04GB
```

**Comment by LanikSJ** [comment]
You're using the image name vs image ID: 
```
→ docker pull devopsqa/fortify
Using default tag: latest
latest: Pulling from devopsqa/fortify
7448db3b31eb: Pull complete
c36604fa7939: Pull complete
29e8ef0e3340: Pull complete
....
67d289a96d91: Pull complete
Digest: sha256:8a4683998bf9a7aebf59a93b1a9c4598af3d34ae661186d1143664fc49f7ce11
Status: Downloaded newer image for devopsqa/fortify:latest
docker.io/devopsqa/fortify:latest

→ docker images -a
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
devopsqa/fortify    latest              9db34bb78a6e        2 years ago         3.04GB

→ dfimage 9db34bb78a6e
Unable to find image 'laniksj/dfimage:latest' locally
latest: Pulling from laniksj/dfimage
df20fa9351a1: Pull complete
f8d8b40b5aa5: Pull complete
f63d9ebd731c: Pull complete
Digest: sha256:61c4d63202d6da641f48293bb5d1b4bf55a917c865578b65764314e2390a8191
Status: Downloaded newer image for laniksj/dfimage:latest
FROM devopsqa/fortify:latest
ADD file:89ecb642d662ee7edbb868340551106d51336c7e589fdaca4111725ec64da957 in /
CMD ["/bin/bash"]
....
```
Above works no problem.

**Comment by ozbillwang** [comment]
Thanks for so quick reply.

Could you adjust your tool that inputs from ImageID to Image name?

**Comment by LanikSJ** [comment]
I wish my Python skills were that good.  Some have tried many haven't been successful.

**Comment by ozbillwang** [comment]
Sure, let me take a look when have time to improve it.
