### ISSUE TITLE
dfimage container not reversing any container tried, including itself

### ISSUE THREAD

**Issue by digitalw00t** [LanikSJ/dfimage#184]
I tried using the script as described in the MD for the following:
docker pull factoriotools/factorio
dfimage factoriotools/factorio

--> I get the following after a good wait:
Traceback (most recent call last):
  File "/root/entrypoint.py", line 57, in <module>
    __main__ = MainObj()
  File "/root/entrypoint.py", line 16, in __init__
    self._get_image(argv[-1])
  File "/root/entrypoint.py", line 29, in _get_image
    if repo_tag in i['RepoTags']:
TypeError: argument of type 'NoneType' is not iterable

So then I thought, let'e try this:
docker pull ghcr.io/laniksj/dfimage
dfimage ghcr.io/laniksj/dfimage

--> and I got the same thing
Traceback (most recent call last):
  File "/root/entrypoint.py", line 57, in <module>
    __main__ = MainObj()
  File "/root/entrypoint.py", line 16, in __init__
    self._get_image(argv[-1])
  File "/root/entrypoint.py", line 29, in _get_image
    if repo_tag in i['RepoTags']:
TypeError: argument of type 'NoneType' is not iterable

Is the system broken or am I missing something obvious?

**Comment by LanikSJ** [comment]
You have to provide a tag for the container you're going to use if you don't provide a tag then it fails like what you've seen above.  I'll update the directions to reflect that.
