### ISSUE TITLE
🐛 [BUG] - dfimage reports Error

### ISSUE THREAD

**Issue by Mollylulu** [LanikSJ/dfimage#203]
### Description

when I run `dfimage MY_IMAGE:TAG`, it reports:
```
File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
TypeError: HTTPConnection.request() got an unexpected keyword argument 'chunked'
```

### Docker Config

```bash
1. Open Docker Desktop
2. Docker Desktop > About
```

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by LanikSJ** [comment]
Knowing which image you're working with would greatly help.  Along with any screenshots or logs you can provide.

**Comment by Mollylulu** [comment]
the following is the error, when I use `dfimage MY_IMAGE:TAG`:
```
Traceback (most recent call last):
  File "/root/entrypoint.py", line 63, in <module>
    __main__ = MainObj()
               ^^^^^^^^^
  File "/root/entrypoint.py", line 16, in __init__
    self._get_image(argv[-1])
  File "/root/entrypoint.py", line 29, in _get_image
    images = self.cli.images()
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/docker/api/image.py", line 40, in images
    res = self._result(self._get(self._url("/images/json"), params=params),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/docker/client.py", line 139, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
TypeError: HTTPConnection.request() got an unexpected keyword argument 'chunked'
```

**Comment by LanikSJ** [comment]
I got this far with it: https://github.com/LanikSJ/dfimage/commit/975dede916b97b6cd2cf4ce9f9db4aae333298ad

And a new error message:
```bash
Traceback (most recent call last):
  File "/Users/LanikSJ/Documents/repos/dfimage/entrypoint.py", line 63, in <module>
    __main__ = MainObj()
               ^^^^^^^^^
  File "/Users/LanikSJ/Documents/repos/dfimage/entrypoint.py", line 15, in __init__
    self.cli = client(base_url='unix://var/run/docker.sock')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable
```

**Comment by LanikSJ** [comment]
Slightly different error if I invoke it differently:
```bash
Traceback (most recent call last):
  File "/Users/LanikSJ/Documents/repos/dfimage/entrypoint.py", line 66, in <module>
    __main__ = MainObj()
               ^^^^^^^^^
  File "/Users/LanikSJ/Documents/repos/dfimage/entrypoint.py", line 16, in __init__
    self.cli = client(base_url="unix://var/run/docker.sock")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable
```
